### PR TITLE
Please disregard this request.

### PR DESCRIPTION
**Pull request by mightyowl866**

### CODE REVIEW

**Comment by Cattn** [comment]
Ok

**Comment by Cattn** [comment]
If you're interested in forking the project for something, and need help with anything, or even want me to try and clean up part of this code (seeing as it's been years) @mightyowl866 lmk

**Comment by mightyowl866** [comment]
Thanks! I really appreciate it! :)

I'll look into setting up a proper fork in the next couple of days. I really like the project so far.

**Comment by Cattn** [comment]
> Thanks! I really appreciate it! :)
> 
> I'll look into setting up a proper fork in the next couple of days. I really like the project so far.

There's a lot of stuff in this project that needs cleaning up lmao, I built this like a year and a half ago, and I've grown a ton since I've made it, so I could probably clean it up well

**Comment by Cattn** [comment]
Like most the features here "work" but either the code behind them is terrible (and I really really mean that), or they're extremely convoluted or janky

**Comment by mightyowl866** [comment]
Gotcha.

I've created a new fork of this repo, and added the work that I've done to it. But once again, thank you very much for offering to help. I appreciate it big time. :)

Once I got some breathing room in my studies, I'll be taking a deep dive into the program.

**Comment by Cattn** [comment]
Sounds good, I might make updates to this repo

**Pull request closed without merging**
